import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/LayoutWrapper/LayoutWrapper";
import NextAuthProvider from "@/provider/NextAuthProvider";

const jakarta = Plus_Jakarta_Sans({
	subsets: ["latin"],
});

export const metadata = {
	title: {
		default: "Care Center – Baby Sitting & Elderly Care Service Platform",
		template: "%s | Baby Sitting & Elderly Care Service Platform",
	},
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<NextAuthProvider>
			<html lang="en" data-theme="light">
				<body className={`${jakarta.className} antialiased`}>
					{/* LayoutWrapper decides when to show Navbar/Footer */}
					<LayoutWrapper>{children}</LayoutWrapper>
				</body>
			</html>
		</NextAuthProvider>
	);
}
