import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const jakarta = Plus_Jakarta_Sans({
	subsets: ["latin"],
});

export const metadata = {
	title: "Care Center",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" data-theme="light">
			<body className={`${jakarta.className} antialiased`}>
				<Navbar />
				<main className="min-h-[calc(100vh-585px)]">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
