import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/LayoutWrapper/LayoutWrapper";

const jakarta = Plus_Jakarta_Sans({
	subsets: ["latin"],
});

export const metadata = {
	title: "Care Center",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" data-theme="light">
			<body className={`${jakarta.className} antialiased`}>
				{/* LayoutWrapper decides when to show Navbar/Footer */}
				<LayoutWrapper>{children}</LayoutWrapper>
			</body>
		</html>
	);
}
